"""
Django settings for client_web project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Mantenha sua chave SECRETA original. Se você copiou o código inteiro, esta pode ter mudado.
# Se sim, encontre a linha 'SECRET_KEY' no seu arquivo original antes de colar tudo e use A SUA CHAVE.
SECRET_KEY = 'django-insecure-(ofpl)#9tsygzvhuu*e@q@8fqe@4*a=c9y3dig1c5hwxck!!hv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'client_web',
    'users.apps.UsersConfig', # === Certifique-se que esta linha aparece APENAS UMA VEZ ===
    'helpdesk.apps.HelpdeskConfig',
]

# Diz ao Django para usar seu modelo CustomUser para autenticação
AUTH_USER_MODEL = 'users.CustomUser'

# URL para redirecionar após um login bem-sucedido (ex: para a página inicial)
LOGIN_REDIRECT_URL = '/' # Redireciona para a raiz do site ('/') após o login

# URL para a página de login (usada por @login_required, etc.)
LOGIN_URL = '/accounts/login/' # Aponta para a URL de login configurada em urls.py

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORRIGIDO: Referencia ao pacote do projeto com a grafia correta ('client_web')
ROOT_URLCONF = 'client_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <--- ADICIONE/MODIFIQUE ESTA LINHA
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# CORRIGIDO: Referencia ao pacote do projeto com a grafia correta ('client_web')
WSGI_APPLICATION = 'client_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # O banco será um arquivo chamado db.sqlite3 na pasta raiz do projeto
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # Ou mude para 'pt-br' se preferir
TIME_ZONE = 'UTC' # Ou mude para 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Adicione esta configuração abaixo de STATIC_URL
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Diz ao Django para procurar por arquivos estáticos na pasta 'static' na raiz do projeto
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'