# Generated by Django 5.2 on 2025-04-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('Open', 'Aberto'), ('In Progress', 'Em Progresso'), ('Closed', 'Fechado'), ('Resolved', 'Resolvido'), ('Waiting for User', 'Aguardando Usuário')], default='Open', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Chamado de Helpdesk',
                'verbose_name_plural': 'Chamados de Helpdesk',
                'ordering': ['-created_at'],
            },
        ),
    ]
