# Generated by Django 5.2 on 2025-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('', '--- Selecione ---'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Rede', 'Rede'), ('E-mail', 'E-mail'), ('Outro', 'Outro')], default='Outro', max_length=100, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Baixa'), ('Medium', 'Média'), ('High', 'Alta'), ('Urgent', 'Urgente')], default='Medium', max_length=20, verbose_name='Prioridade'),
        ),
    ]
